; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
upload_protocol = esptool
upload_port = /dev/ttyUSB0
;upload_port = 192.167.4.1
upload_speed = 115200
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit GFX Library @ ^1.11.3
	adafruit/Adafruit SSD1306@^2.5.7
	igorantolic/Ai Esp32 Rotary Encoder@1.4.0
	adafruit/MAX6675 library@^1.1.0
	dlloydev/QuickPID @ ^3.1.9
	https://github.com/ayushsharma82/AsyncElegantOTA.git#v2.2.7
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	arduino-libraries/Arduino_JSON @ 0.1.0